server:
  port: 8080
  ssl:
    key-store: classpath:dongbao-alias.keystore
    # java key store = JKS
    key-store-type: JKS
    # 生成key-sotre的指定了别名的
    key-alias: dongbao-alias
    key-password: 123456
    key-store-password: 123456
spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #记得先创建数据库
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
